apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  generateName: gitops-1.17.1-prod-
  namespace: rh-openshift-gitops-tenant
spec:
  gracePeriodDays: 7
  releasePlan: gitops-1-17-prod
  snapshot: gitops-1-17-9n2xp
  data:
    releaseNotes:
      type: RHSA
      issues:
        fixed:
          - id: GITOPS-7571
            source: issues.redhat.com 
          - id: GITOPS-7582
            source: issues.redhat.com 
          - id: GITOPS-7585
            source: issues.redhat.com 
          - id: GITOPS-7594
            source: issues.redhat.com 
          - id: GITOPS-7600
            source: issues.redhat.com 
      cves:
        - key: CVE-2025-55190
          component: argocd-1-17
        - key: CVE-2025-55190
          component: argocd-rhel9-1-17
        - key: CVE-2025-55190
          component: gitops-operator-1-17
        - key: CVE-2025-55190
          component: gitops-operator-bundle-1-17
      topic: "Red Hat OpenShift GitOps v1.17.1 release"
      synopsis: "Red Hat OpenShift GitOps security update"
      description: |
        An update is now available for Red Hat OpenShift GitOps.  
          
        Security Fix(es):  
        * openshift-gitops-1/argocd-rhel8: Project API Token Exposes Repository Credentials [gitops-1.17](CVE-2025-55190) 
        * openshift-gitops-1/argocd-rhel9: Project API Token Exposes Repository Credentials [gitops-1.17](CVE-2025-55190) 
        * openshift-gitops-1/gitops-operator-bundle: Project API Token Exposes Repository Credentials [gitops-1.17](CVE-2025-55190) 
        * openshift-gitops-1/gitops-rhel8-operator: Project API Token Exposes Repository Credentials [gitops-1.17](CVE-2025-55190)
      solution: |
        Before applying this update, make sure all previously released errata relevant to your system have been applied.
        
        For details on how to apply this update, refer to:
        
        https://access.redhat.com/articles/11258
      references:
        - https://access.redhat.com/security/cve/CVE-2025-55190
        - https://docs.redhat.com/en/documentation/red_hat_openshift_gitops/1.17/