# Release Metadata
release:
  name: OpenShift GitOps Operator
  version: "1.16.2"
  manager:
    name: "Siddhesh Ghadi"
    github: svghadi
    email: "sghadi@redhat.com"

# Artifact - container images and rpms built from the source code
artifacts:
  - name: "Red Hat OpenShift GitOps Service"
    id: backend
    path: "gitops-backend"
    type: image
    releaseRef: "registry.redhat.io/openshift-gitops-1/gitops-rhel8"
    konflux-ci:
      component: gitops-backend
      buildRef: "quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-backend"

  - name: "Red Hat OpenShift GitOps DevConsole Plugin"
    id: console-plugin
    path: "gitops-console-plugin"
    type: image
    releaseRef: "registry.redhat.io/openshift-gitops-1/console-plugin-rhel8"
    konflux-ci:
      component: gitops-console-plugin
      buildRef: "quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-console-plugin"

  - name: "Red Hat OpenShift GitOps Dex"
    id: dex
    path: "dex"
    type: image
    releaseRef: "registry.redhat.io/openshift-gitops-1/dex-rhel8"
    konflux-ci:
      component: dex
      buildRef: "quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/dex"

  - name: "Red Hat OpenShift Must Gather"
    id: must-gather
    path: gitops-must-gather
    type: image
    releaseRef: "registry.redhat.io/openshift-gitops-1/must-gather-rhel8"
    konflux-ci:
      component: gitops-must-gather
      buildRef: "quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-must-gather"

  - name: "Red Hat OpenShift GitOps Operator"
    id: operator
    path: "gitops-operator"
    type: image
    releaseRef: "registry.redhat.io/openshift-gitops-1/gitops-rhel8-operator"
    konflux-ci:
      component: "gitops-operator"
      buildRef: "quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator"

  - name: "Red Hat OpenShift GitOps Argo CD"
    id: argocd
    path: "argo-cd"
    type: image
    releaseRef: "registry.redhat.io/openshift-gitops-1/argocd-rhel8"
    konflux-ci:
      component: argocd-cd
      buildRef: "quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/argo-cd"

  - name: "Red Hat OpenShift GitOps Argo Rollouts"
    id: rollouts
    path: "argo-rollouts"
    type: image
    releaseRef: "registry.redhat.io/openshift-gitops-1/argo-rollouts-rhel8"
    konflux-ci:
      component: argo-rollouts
      buildRef: "quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/argo-rollouts"

  - name: "Red Hat OpenShift GitOps Operator Bundle"
    id: bundle
    path: "gitops-operator-bundle"
    type: image
    releaseRef: "registry.redhat.io/openshift-gitops-1/gitops-operator-bundle"
    konflux-ci:
      component: "gitops-operator-bundle"
      buildRef: "quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/gitops-operator-bundle"

  - name: "Red Hat OpenShift GitOps ArgoCD Extensions"
    id: extensions
    path: "argocd-extension-installer"
    type: image
    releaseRef: "registry.redhat.io/openshift-gitops-1/argocd-extensions-rhel8"
    konflux-ci:
      component: "argocd-extension-installer-1-16"
      buildRef: "quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/argocd-extension-installer"

# Sources - source code repositories
sources:
  - path: sources/gitops-operator 
    url: https://github.com/redhat-developer/gitops-operator.git
    ref: v1.16
    commit: a4755e5fc5ea85601037d31208901ee4ac07106e
  - path: sources/argo-cd 
    url: https://github.com/argoproj/argo-cd.git
    ref: release-2.14
    commit: 2aceb1dc444cd341dbe10030eeaaa9870f42b53d
  - path: sources/argo-rollouts 
    url: https://github.com/argoproj/argo-rollouts.git
    ref: v1.7.2
    commit: 59e5bd385c031600f86075beb9d77620f8d7915e
  - path: sources/kustomize
    url: https://github.com/kubernetes-sigs/kustomize.git
    ref: v5.4.3
    commit: d4248b1213768c184f5ebbb8ee1a1422817478e4
  - path: sources/helm
    url: https://github.com/helm/helm.git
    ref: v3.16.4
    commit: 7877b45b63f95635153b29a42c0c2f4273ec45ca
  - path: sources/dex
    ref: v2.41.1
    url: https://github.com/dexidp/dex.git
    commit: 43956db7fd75c488a82c70cf231f44287300a75d
  - path: sources/git-lfs
    url: https://github.com/git-lfs/git-lfs.git
    ref: v3.6.1
    commit: ea47a34bde1ba1ecf9eb8dc6d44fcf7aef42f5e3
  - path: sources/ssh-connect
    url: https://github.com/gotoh/ssh-connect.git
    ref: master
    commit: b65b09a0ee06950972233e8ea86ef87c4e63b3c9
  - path: sources/tini
    url: https://github.com/krallin/tini.git
    ref: master
    commit: 0b44d3665869e46ccbac7414241b8256d6234dc4
  - path: sources/argocd-extension-installer
    url: https://github.com/argoproj-labs/argocd-extension-installer.git
    ref: main
    commit: 44a5ab8e6998df0beb6f293b3607262db53aa8c7
  - path: sources/gitops-console-plugin
    url: https://github.com/redhat-developer/gitops-console-plugin.git
    ref: main
    commit: d858af08d29c94618e6ad63bd3c9330420422088
  - path: sources/gitops-backend
    url: https://github.com/redhat-developer/gitops-backend.git
    ref: master
    commit: d83d568a6131e2564353a6ec1294d28635783616
  - path: sources/rollouts-plugin-trafficrouter-openshift
    url: https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-openshift.git
    ref: main
    commit: 142230a39d74119ccfc7414f6812bdac2fc09449
  - path: sources/gitops-must-gather
    url: https://github.com/redhat-developer/gitops-must-gather.git
    ref: main
    commit: 4b954166b1ccab7dd628df912e5be13381b57211
  - path: sources/rollout-extension
    url: https://github.com/argoproj-labs/rollout-extension.git
    ref: main
    commit: 6f6289da54237a7ed084b22f3161317bfa9a9b4f

# Dependencies - required container images
dependencies:
  - name: "OpenShift HAProxy Router"
    id: haproxy
    type: image
    ref: registry.redhat.io/openshift4/ose-haproxy-router@sha256:72817b62a55fb0f82f2908effc7bd3d20409fc60e9f228449d8f78eb390e22ac
  - name: "Red Hat SSO 7.6"
    id: keycloak
    type: image
    ref: registry.redhat.io/rh-sso-7/sso76-openshift-rhel8@sha256:cf52b301f1c37c1de925bcf7e16005b0a3a1865645db29fd671d47db592da1e7
  - name: "Redis 7"
    id: redis
    type: image
    ref: registry.redhat.io/rhel9/redis-7@sha256:af174f3bc30f88c42b86add90d910cab79b1066d939b7faa99d85f5e8778e6d0
  - name: "Proxy for Kubernetes RBAC authorization"
    id: kube-proxy
    type: image
    ref: registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:baa41441752d6d739065eda587b92402e209c67fbcdacf0a40559d37c9e978eb
  - name: "must-gather for OpenShift GitOps"
    id: ose-must-gather
    type: image
    ref: registry.redhat.io/openshift4/ose-must-gather@sha256:0679c00c1c6c52780c3d36f44ce6a6f702e9f968b78a377310b511ebb81b5e98
