apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/nmirasch/release?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "GITOPS-7196"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: testing-rpms-builds
    appstudio.openshift.io/component: argocd-cli-dev-gitops-7196
    pipelines.appstudio.openshift.io/type: build
  name: argocd-cli-dev-gitops-7196-on-pull-request
  namespace: rh-openshift-gitops-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/argocd-cli-dev-gitops-7196:{{revision}}
  - name: image-expires-after
    value: 5d
  - name: build-platforms
    value:
    - linux/x86_64
  - name: additional-tags
    value:
    - '{{target_branch}}'
  - name: dockerfile
    value: containers/argocd-cli/Dockerfile
  - name: prefetch-input
    value: '[{"type":"gomod","path":"./sources/argo-cd"}, {"type":"yarn","path":"./sources/argo-cd/ui"},{"type":"rpm","path":"prefetch/rpms/ubi8"}, {"type":"npm","path":"prefetch/yarn"}]'
  - name: git-metadata-directories
    value:
    - sources/argo-cd
  pipelineRef:
    name: build-multi-platform-image
  taskRunTemplate:
    serviceAccountName: build-pipeline-argocd-cli-dev-gitops-7196
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}