apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/nmirasch/release?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "GITOPS-6959_microshift-gitops_rpm"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: testing-rpms-builds
    appstudio.openshift.io/component: local-release-microshift-gitops-rpm
    pipelines.appstudio.openshift.io/type: build
  name: local-release-microshift-gitops-rpm-on-push
  namespace: rh-openshift-gitops-tenant
spec:
  params:
  - name: ociStorage
    value: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/microshift-gitops-rpm:{{revision}}
  - name: package-name
    value: microshift-gitops
  - name: path-context
    value: rpms/microshift-gitops
  - name: git-url
    value: "{{ source_url }}"
  - name: revision
    value: "{{ revision }}"
  - name: target-branch
    value: "{{ target_branch }}"
  - name: hermetic
    value: "true"
  - name: build-architectures
    value:
    - aarch64
    - x86_64
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: "https://github.com/konflux-ci/rpmbuild-pipeline.git"
    - name: revision
      value: main
    - name: pathInRepo
      value: pipeline/build-rpm-package.yaml
  workspaces:
  - name: source
    persistentVolumeClaim:
      claimName: "{{pvc_name}}"
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
