apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/nmirasch/release?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "rpm-microshift-gitops-dist-git" && ( "rpms/microshift-gitops/***".pathChanged()
      || ".tekton/rpm-microshift-gitops-distgit-push.yaml".pathChanged() )

  labels:
    appstudio.openshift.io/application: test-rpms-builds
    appstudio.openshift.io/component: rpm-microshift-gitops-distgit
    pipelines.appstudio.openshift.io/type: build
  name: rpm-microshift-gitops-distgit-on-push
  namespace: rh-openshift-gitops-tenant
spec:
  params:
  - name: ociStorage
    value: quay.io/redhat-user-workloads/rh-openshift-gitops-tenant/rpm-microshift-gitops-distgit:{{revision}}
  - name: monorepo-subdir
    value: rpms/microshift-gitops
  - name: specfile
    value: microshift-gitops.spec
  - name: package-name
    value: microshift-gitops
  - name: git-url
    value: "https://github.com/nmirasch/distgit-rpm-testing"
  - name: revision
    value: "main"
  - name: target-branch
    value: "main"
  - name: mock-config-template-filename-in-sources
    value: "rpms/microshift-gitops/mock.cfg"
  - name: hermetic
    value: "true"
  - name: build-architectures
    value:
    - aarch64
    - x86_64
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: "https://github.com/konflux-ci/rpmbuild-pipeline.git"
    - name: revision
      value: main
    - name: pathInRepo
      value: pipeline/build-rpm-package.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-rpm-microshift-gitops-distgit
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
